server:
  port: 8082

spring:
  application:
    name: client-service

  datasource:
    url: jdbc:postgresql://localhost:5432/clientdb
    username: pymelite_useradmin
    password: pymelite_useradmin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
